services:
  pg:
    image: postgres:latest
    container_name: pg_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-url-shortener}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:8.9
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '7777:80'
    volumes:
      - pgadmin_local:/var/lib/pgadmin
    depends_on:
      - pg
    restart: always

  simple-webapp:
    container_name: simple-webapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    volumes:
      - ./:/usr/src/simple-webapp
    depends_on:
      - pg
    command: sh -c "npm install && npm run migrate && npm start"

volumes:
  postgres_data:
  pgadmin_local:
